version: '3'

services:
  db:
    build:
      context: "./db"
    tty: true
    restart: always
    container_name: gventas_db
    volumes:
      - "./db/_data:/var/lib/mysql"
    ports:
      - "3307:3306"      
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
  app:
    build:
      context: "./app"
    tty: true
    restart: always
    container_name: gventas_app      
    volumes:
      - "./app:/go/src/app"
    ports:
      - "8801:8080"
    depends_on:
      - db